version: '3.8'

services:
  backend:
    container_name: 'notimy_backend_prod'
    restart: always
    env_file: .env
    build: ./backend
    environment:
      - POSTGRES_HOST=kemogeko.beget.app
    volumes:
      - ./certs:/etc/ssl
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: [ "sh", "-c", "poetry run alembic upgrade head && poetry run python -m app" ]


  nginx:
    container_name: 'notimy_nginx_prod'
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl
    depends_on:
      - backend