version: '3'

services:
  database:
    container_name: 'notimy_postgres'
    image: 'postgres:14'
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - database
    command: ["sh", "-c", "alembic upgrade head && poetry run python3 -m notimy"]

#  frontend:
#    build: ./frontend
#    depends_on:
#      - backend

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl:/etc/ssl
    depends_on:
      - backend


volumes:
  postgres_data: