"""empty message

Revision ID: 54ea6617ed6f
Revises: d0a67113c055
Create Date: 2024-07-28 00:56:20.211291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ea6617ed6f'
down_revision: Union[str, None] = 'd0a67113c055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('account', sa.UUID(), nullable=False))
    op.add_column('spots', sa.Column('account', sa.UUID(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.add_column('users', sa.Column('data', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'data')
    op.drop_column('users', 'role')
    op.drop_column('spots', 'account')
    op.drop_column('providers', 'account')
    # ### end Alembic commands ###
