"""initial

Revision ID: d0a67113c055
Revises: 
Create Date: 2024-07-03 12:25:18.430324

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd0a67113c055'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.UUID(), nullable=False),
    sa.Column('spot', sa.UUID(), nullable=False),
    sa.Column('closed_by', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('users_raw', sa.String(), nullable=False),
    sa.Column('messages_raw', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('closed_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__channels'))
    )
    op.create_index(op.f('ix__channels__code'), 'channels', ['code'], unique=True)
    op.create_index(op.f('ix__channels__provider'), 'channels', ['provider'], unique=False)
    op.create_index(op.f('ix__channels__spot'), 'channels', ['spot'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_channel', sa.Integer(), nullable=False),
    sa.Column('spots', sa.Integer(), nullable=False),
    sa.Column('max_spots', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__providers'))
    )
    op.create_index(op.f('ix__providers__token'), 'providers', ['token'], unique=False)
    op.create_table('spots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('additional_info', sa.String(), nullable=True),
    sa.Column('provider', sa.UUID(), nullable=False),
    sa.Column('channels_raw', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__spots'))
    )
    op.create_index(op.f('ix__spots__token'), 'spots', ['token'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channels_raw', sa.String(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix__spots__token'), table_name='spots')
    op.drop_table('spots')
    op.drop_index(op.f('ix__providers__token'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix__channels__spot'), table_name='channels')
    op.drop_index(op.f('ix__channels__provider'), table_name='channels')
    op.drop_index(op.f('ix__channels__code'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
