"""empty message

Revision ID: 1c6a4ad04bed
Revises: 737aab11cb50
Create Date: 2024-08-27 11:08:02.497185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6a4ad04bed'
down_revision: Union[str, None] = '737aab11cb50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix__channels__spot', table_name='channels')
    op.drop_constraint('fk__channels__spot__spots', 'channels', type_='foreignkey')
    op.drop_column('channels', 'spot')
    op.add_column('spots', sa.Column('provider_id', sa.UUID(), nullable=False))
    op.alter_column('spots', 'account',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix__spots__account'), 'spots', ['account'], unique=False)
    op.create_index(op.f('ix__spots__provider_id'), 'spots', ['provider_id'], unique=False)
    op.create_foreign_key(op.f('fk__spots__account__users'), 'spots', 'users', ['account'], ['id'])
    op.create_foreign_key(op.f('fk__spots__provider_id__providers'), 'spots', 'providers', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__spots__provider_id__providers'), 'spots', type_='foreignkey')
    op.drop_constraint(op.f('fk__spots__account__users'), 'spots', type_='foreignkey')
    op.drop_index(op.f('ix__spots__provider_id'), table_name='spots')
    op.drop_index(op.f('ix__spots__account'), table_name='spots')
    op.alter_column('spots', 'account',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('spots', 'provider_id')
    op.add_column('channels', sa.Column('spot', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk__channels__spot__spots', 'channels', 'spots', ['spot'], ['id'])
    op.create_index('ix__channels__spot', 'channels', ['spot'], unique=False)
    # ### end Alembic commands ###
