"""empty message

Revision ID: 43f462e6f7cd
Revises: a9219c8f53de
Create Date: 2024-09-29 00:46:07.516459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f462e6f7cd'
down_revision: Union[str, None] = 'a9219c8f53de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('push_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_data')
    # ### end Alembic commands ###
