"""add subsctription

Revision ID: 54f3a7c918ee
Revises: 32b28e705cde
Create Date: 2024-08-21 00:27:35.167563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f3a7c918ee'
down_revision: Union[str, None] = '32b28e705cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('spot_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk__subscriptions__provider_id__providers')),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], name=op.f('fk__subscriptions__spot_id__spots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__subscriptions')),
    sa.UniqueConstraint('provider_id', name=op.f('uq__subscriptions__provider_id')),
    sa.UniqueConstraint('spot_id', name=op.f('uq__subscriptions__spot_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
