"""empty message

Revision ID: a9219c8f53de
Revises: 1c6a4ad04bed
Create Date: 2024-09-02 16:42:40.956024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9219c8f53de'
down_revision: Union[str, None] = '1c6a4ad04bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('local_number', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'local_number')
    # ### end Alembic commands ###
