"""telegram_api

Revision ID: b53043409896
Revises: 43f462e6f7cd
Create Date: 2024-10-05 23:48:26.172880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b53043409896'
down_revision: Union[str, None] = '43f462e6f7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('telegram_username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('telegram_firstname', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('telegram_lastname', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix__users__telegram_id'), 'users', ['telegram_id'], unique=False)
    op.create_index(op.f('ix__users__telegram_username'), 'users', ['telegram_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__users__telegram_username'), table_name='users')
    op.drop_index(op.f('ix__users__telegram_id'), table_name='users')
    op.drop_column('users', 'telegram_lastname')
    op.drop_column('users', 'telegram_firstname')
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###
