"""empty message

Revision ID: e2aa0e769a40
Revises: 54ea6617ed6f
Create Date: 2024-08-11 22:13:17.976847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2aa0e769a40'
down_revision: Union[str, None] = '54ea6617ed6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__aliases'))
    )
    op.create_index(op.f('ix__aliases__base'), 'aliases', ['base'], unique=False)
    op.create_index(op.f('ix__aliases__name'), 'aliases', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__aliases__name'), table_name='aliases')
    op.drop_index(op.f('ix__aliases__base'), table_name='aliases')
    op.drop_table('aliases')
    # ### end Alembic commands ###
